config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  post '/users/:user_id/ratings' => 'ratings#create'

  post '/login' => 'users#login'
  post '/logout' => 'users#destroy'

  post '/users/:user_id/ratings' => 'ratings#create', as: :ratings

  post '/login' => 'users#login'
  post '/trips/:id/join' => 'passengers#join', as: :join

    resources :users do
      resources :trips
    end
    resources :trips

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :passengers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trips
  has_many :passengers
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def join
    Passenger.create!(user_id: session[:user_id],
      trip_id: params[:id]
    )
    @trip = Trip.where(id: params[:id]).first
    seats = @trip.seats - 1
    @trip.update_attributes(seats: seats)
    redirect_to trip_path(params[:id])
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @rating = Rating.new(
      value: params[:rating][:value],
      user_type: params[:rating][:user_type],
      comment: params[:rating][:comment],
      user_id: params[:user_id]
    )
    if @rating.save
      redirect_to user_path(@rating.user)
    end
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    @trips = Trip.all
  end

  def new
    @user = User.find(session[:user_id])
    @trip = Trip.new
  end

  def create
    @user = User.find(session[:user_id])

    @trip = Trip.new(
      user_id: @user.id,
      origin: params[:trip][:origin],
      destination: params[:trip][:destination],
      price: params[:trip][:price],
      seats: params[:trip][:seats],
      car_photo: params[:trip][:car_photo],
      time: params[:trip][:time],
      date: params[:trip][:date]
      )

    if @trip.save
      redirect_to trips_path
    end
  end

  def show
    @trip = Trip.where(id: params[:id]).first
    @user = @trip.user
    @passengers = Passenger.where(trip_id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def update
    @user = User.where(id: params[:id]).first
    @user.update_attributes(
      profile_picture: params[:user][:profile_picture],
      introduction: params[:user][:introduction],
      contact_info: params[:user][:contact_info]
    )
      redirect_to user_path(@user.id)
  end

  def login
    @user = User.where(username: params[:user][:username]).first
    if @user && @user.password_hash == params[:user][:password_hash]
      # @current_user = @user
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      @error = "Invalid Username or Password"
      @user = User.new
      render :index
    end
  end

  def show
    @user = User.where(id: session[:user_id]).first
    @user = User.where(id: params[:id]).first
    @driver_ratings = Rating.where(user_id: params[:id], user_type: 1)
    @passenger_ratings = Rating.where(user_id: params[:id], user_type: 2)
    @rating = Rating.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      username: params[:user][:username],
      password_hash: params[:user][:password_hash]
      )

      if params[:user][:password_hash] == params[:user][:password_confirmation]
        @user.save
        session[:user_id] = @user.id
        # @current_user = @user
        redirect_to user_path(@user.id)
      else
        @error = "Password confirmation must match Password"
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passenger_helper.rb
module PassengerHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

</body><head>
  <title>Roadtripper</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:user_id] %>
  <%=link_to "Log Out", user_path(session[:user_id]), method: :delete %>
<% end %>

<%= yield %>

</html>

app/views/trips/index.html.erb
<h1>Available Trips</h1>
<% @trips.each do |trip| %>
  <div class="trip">
    <div>Origin: <%= trip.origin %></div>
    <div>Destination: <%= trip.destination %></div>
    <div>Price: <%= trip.price %></div>
    <div>Seats Remaining: <%= trip.seats %></div>
    <div>Departure Time: <%= trip.time %></div>
    <div>Date: <%= trip.date %></div>
    <%= link_to "Details", trip_path(trip.id) %>
  </div>
<% end %>

<a href="/users/<%=@user.id%>">Return to profile page</a>

app/views/trips/new.html.erb
<%= form_for @trip do |f| %>
  <%= f.label :origin %>
  <%= f.text_field :origin, required: true %>

  <%= f.label :destination %>
  <%= f.text_field :destination, required: true %>

  <%= f.label :cost %>
  <%= f.text_field :price %>

  <%= f.label :car_photo %>
  <%= f.text_field :car_photo %>

  <%= f.label :seats %>
  <%= f.text_field :seats %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :time %>
  <%= f.text_field :time %>

  <%= f.submit %> 
<% end %>

<a href="/users/<%=@user.id%>">Return to profile page</a>

app/views/trips/show.html.erb
<div class="background">
<div class="trip-container">
  <h1><%= @user.username %>'s Roadtrip</h1>
  <h3>From <%= @trip.origin %> to <%= @trip.destination %></h3>
  <h3>Departing: <%= @trip.date %> at <%= @trip.time %></h3>
  <img class="car" src=<%= @trip.car_photo %>>
  <h2>Seats available: <%= @trip.seats %></h2>
  <p>Price: <%= @trip.price %></p>
</div>

<div class="passengers-container">
  <h3>Passengers:</h3>
  <% @passengers.each do |passenger| %>
    <div class="passenger">
      <div class="icon"><img src=<%= passenger.user.profile_picture %>></div>
      <%= passenger.user.username %>
      <%= link_to "Profile", user_path(passenger.user.id) %>
    </div>
  <% end %>
  <%= button_to "Join this trip!", join_path(@trip.id) %>
</div>
</div>
<a href="/trips?">Return to view all trips</a>

<div id="chat" class="container">
 
  <h1>Come and Join the Conversation</h1>

  <div class="panel panel-default">

    <div class="panel-body">
      <div id="comments-container"></div>
    </div>

    <div class="panel-footer">

      <form role="form">
          <div class="form-group">
              <label for="comments">Please enter your comments here</label>
              <input class="form-control" id="comments" name="comments">
          </div>

          <button type="submit" id="submit-btn" name="submit-btn"
              class="btn btn-success">Send Comments</button>

          <button type="reset" class="btn btn-danger">Clear Comments</button>
      </form>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="header">RoadTripper</h1>
  <% if @error %>
    <%= @error %>
  <% end %>
<div class="login">
<%= form_for @user , url: login_path(@user) do |f| %>
  
    <%= f.label :username %>
    <%= f.text_field :username, required: true, title: "Please Enter Your Username" %>

    <%= f.label :password %>
    <%= f.password_field :password_hash, required: true %>

    <%= f.submit "Login" %>
<% end %>
</div>
<button type="button" class="btn btn-default btn-lg btn-block">
<%= link_to "SIGN UP", href="/users/new" %>
</button>

<img src="https://unsplash.imgix.net/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?fit=crop&fm=jpg&h=500&q=75&w=1050", alt="roadtrip", width="100%""> 

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @error %>
    <%= @error %>
  <% end %>

    <div class = "signup">
    <%= f.label :username %>
    <%= f.text_field :username, required: true, title: "Please Enter Your Username" %>

    <%= f.label :password %>
    <%= f.password_field :password_hash, required: true %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit %>
    </div>
<% end %>
   

app/views/users/show.html.erb
<div class="profile">
  <h1 class="jumbotron">Welcome, <%= @user.username %></h1>
  <img class="profile" src=<%= @user.profile_picture %>>
  <p><%= @user.introduction %></p>
</div>


<div class="driver-ratings">
  <h3>Ratings as Driver:</h3>
  <% @driver_ratings.each do |rating| %>
    <div class="rating">
      <% rating.value.times do |stars| %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <p><%= rating.comment %></p>
    </div>
  <% end %>
</div>

<div class="passenger-ratings">
  <h3>Ratings as passenger:</h3>
  <% @passenger_ratings.each do |rating| %>
    <div class="rating">
      <% rating.value.times do |stars| %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <p><%= rating.comment %></p>
    </div>
  <% end %>
</div>

<% if @user.id == session[:user_id] %>
  <button class="edit">Edit Profile</button>
  <%= form_for @user, url: user_path(@user), method: :put do |f| %>

    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture %>

    <%= f.label :introduction %>
    <%= f.text_field :introduction %>

    <%= f.label :contact_info %>
    <%= f.text_field :contact_info %>

    <%= f.submit %>
  <% end %>
<% end %>

<% if @user.id != session[:user_id] %>
  <%= form_for @rating, url: ratings_path(@user) do |f| %>
    <%= f.radio_button :user_type, '1' %>
    <%= label :driver_rating, 'Driver' %>

    <%= f.radio_button :user_type, '2' %>
    <%= label :passenger_rating, 'Passenger' %>

    <%= f.label :rating %>
    <%= f.text_field :value %>

    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <%= f.submit %>
  <% end %>
<% end %>

<%= button_to "Create new trip", new_trip_path, method: :get %>
<%= button_to "Look for trips", trips_path, method: :get %>